<?php
/**
 * @file
 * Login Redirection Module hooks.
 */
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;


use Drupal\Core\Url;

function login_redirection_user_login($account) {
	 // We want to redirect user on login
  $current_user = \Drupal::currentUser();
  $username = $current_user->getRoles();
  $login_redirection= \Drupal::config('login_redirection.settings')->get('login_redirection');
//  kint($login_redirection);die();
  if(isset($login_redirection[array_reverse($username)[0]])){
   $response=new RedirectResponse(URL::fromUserInput($login_redirection[array_reverse($username)[0]])->toString());
     $response->send();  
   }
   else{
     $homeResponse=new RedirectResponse(URL::fromUserInput('/')->toString());
     $homeResponse->send();
   }
     
  return;
}

